spring:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  datasource:
    url: jdbc:mysql://localhost:3306/distance-calculator
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      order_inserts: true
      jdbc.batch_size: 500
    hibernate:
      ddl-auto: update
